default: &default
  adapter: postgresql
  database: mailed_development
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: mailed_development

test:
  <<: *default
  database: mailed_test

production:
  <<: *default
  database: mailed
  host: <%= ENV['POSTGRES_HOST'] %>
  database: <%= ENV['POSTGRES_DATABASE'] %>
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
