# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e234e3a6b9a041250af321641a51829a12fcae14fd4b614d5abdb3a6310c70b45b8e0fb02e99bde8a7e9bc1e18dedffb09bfe5b95b311614fc33c971ef72819e

test:
  secret_key_base: d981def367b6de6945d312d5fcd1c3facead2b41a79dc3dc3780005b73dfa082555c69b658f6e7b06743e3c52642893d8162f113356fa8970cb846ad31908085

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
